version: '3.4'

services:
  sqlserver:
    user: '0:0'
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "${SQLSERVER_PASSWORD}"
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql