version: '3.4'
 
networks:
  creanovelnetcore-dev:
    driver: bridge 
 
services:
  creanovelnetcore:
    depends_on:
      - "sqlserver"
    image: creanovelnetcore:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=1433;database=dbCreanovel;username=sa;password=Panque123!"
    networks:
      - creanovelnetcore-dev  
  
  sqlserver:
    user: '0:0'
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "${SQLSERVER_PASSWORD}"
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql
    networks:
      - creanovelnetcore-dev
volumes:
  db_volume: