// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(CreanovelDbContext))]
    [Migration("20260919071527_AddPersonajesEnEscena")]
    partial class AddPersonajesEnEscena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Background", b =>
                {
                    b.Property<Guid>("BackgroundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("BackgroundId");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("Domain.Models.BackgroundSprite", b =>
                {
                    b.Property<Guid>("BackgroundSpriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionImagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("BackgroundSpriteId");

                    b.HasIndex("BackgroundId");

                    b.ToTable("BackgroundSprites");
                });

            modelBuilder.Entity("Domain.Models.Escena", b =>
                {
                    b.Property<Guid>("EscenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Identificador")
                        .HasColumnType("text");

                    b.Property<Guid>("NovelaVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PrimerEscena")
                        .HasColumnType("boolean");

                    b.Property<bool>("UltimaEscena")
                        .HasColumnType("boolean");

                    b.HasKey("EscenaId");

                    b.HasIndex("NovelaVersionId");

                    b.ToTable("Escenas");
                });

            modelBuilder.Entity("Domain.Models.Lectura", b =>
                {
                    b.Property<Guid>("LecturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("NovelaRegistrosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NovelaVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecursoActualId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioPropietarioId")
                        .HasColumnType("uuid");

                    b.HasKey("LecturaId");

                    b.HasIndex("NovelaRegistrosId");

                    b.HasIndex("UsuarioPropietarioId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("Domain.Models.LecturaRecursos", b =>
                {
                    b.Property<Guid>("LecturaId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecursoOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid");

                    b.HasKey("LecturaId", "RecursoOrder");

                    b.HasIndex("RecursoId");

                    b.ToTable("LecturaRecurso");
                });

            modelBuilder.Entity("Domain.Models.Novela", b =>
                {
                    b.Property<Guid>("NovelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("PortadaImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioCreadorId")
                        .HasColumnType("uuid");

                    b.HasKey("NovelaId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Novelas");
                });

            modelBuilder.Entity("Domain.Models.NovelaBackground", b =>
                {
                    b.Property<Guid>("NovelaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.HasKey("NovelaId", "BackgroundId");

                    b.HasIndex("BackgroundId");

                    b.ToTable("NovelaBackground");
                });

            modelBuilder.Entity("Domain.Models.NovelaPersonaje", b =>
                {
                    b.Property<Guid>("NovelaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonajeId")
                        .HasColumnType("uuid");

                    b.HasKey("NovelaId", "PersonajeId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("NovelaPersonaje");
                });

            modelBuilder.Entity("Domain.Models.NovelaVersion", b =>
                {
                    b.Property<Guid>("NovelaVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definiciones")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsBorrador")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NovelaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroVersion")
                        .HasColumnType("text");

                    b.HasKey("NovelaVersionId");

                    b.HasIndex("NovelaId");

                    b.ToTable("NovelaVersiones");
                });

            modelBuilder.Entity("Domain.Models.Personaje", b =>
                {
                    b.Property<Guid>("PersonajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("PersonajeId");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("Domain.Models.PersonajeSprite", b =>
                {
                    b.Property<Guid>("PersonajeSpriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionImagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonajeId")
                        .HasColumnType("uuid");

                    b.HasKey("PersonajeSpriteId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("PersonajeSprites");
                });

            modelBuilder.Entity("Domain.Models.Recurso", b =>
                {
                    b.Property<Guid>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackgroundSpriteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EscenaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Personajes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("PrimerRecurso")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SiguienteRecursoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRecurso")
                        .HasColumnType("text");

                    b.Property<bool>("UltimoRecurso")
                        .HasColumnType("boolean");

                    b.HasKey("RecursoId");

                    b.HasIndex("BackgroundSpriteId");

                    b.HasIndex("EscenaId");

                    b.HasIndex("SiguienteRecursoId");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("Domain.Models.RecursoDecisionOpcion", b =>
                {
                    b.Property<Guid>("RecursoDecisionOpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condicion")
                        .HasColumnType("jsonb");

                    b.Property<string>("CondicionModo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Efectos")
                        .HasColumnType("jsonb");

                    b.Property<string>("OpcionMensaje")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecursoDecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SiguienteRecursoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecursoDecisionOpcionId");

                    b.HasIndex("RecursoDecisionId");

                    b.HasIndex("SiguienteRecursoId");

                    b.ToTable("RecursoDecisionOpciones");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.BackgroundSprite", b =>
                {
                    b.HasOne("Domain.Models.Background", "Background")
                        .WithMany("Sprites")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("Domain.Models.Escena", b =>
                {
                    b.HasOne("Domain.Models.NovelaVersion", "NovelaVersion")
                        .WithMany("Escenas")
                        .HasForeignKey("NovelaVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NovelaVersion");
                });

            modelBuilder.Entity("Domain.Models.Lectura", b =>
                {
                    b.HasOne("Domain.Models.Novela", "NovelaRegistros")
                        .WithMany()
                        .HasForeignKey("NovelaRegistrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Usuario", "UsuarioPropietario")
                        .WithMany("Lecturas")
                        .HasForeignKey("UsuarioPropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NovelaRegistros");

                    b.Navigation("UsuarioPropietario");
                });

            modelBuilder.Entity("Domain.Models.LecturaRecursos", b =>
                {
                    b.HasOne("Domain.Models.Lectura", "Lectura")
                        .WithMany("Recursos")
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Recurso", "Recurso")
                        .WithMany("Lecturas")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Lectura");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Domain.Models.Novela", b =>
                {
                    b.HasOne("Domain.Models.Usuario", "UsuarioCreador")
                        .WithMany("NovelasCreadas")
                        .HasForeignKey("UsuarioCreadorId");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Domain.Models.NovelaBackground", b =>
                {
                    b.HasOne("Domain.Models.Background", "Background")
                        .WithMany("Novelas")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Novela", "Novela")
                        .WithMany("Backgrounds")
                        .HasForeignKey("NovelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Novela");
                });

            modelBuilder.Entity("Domain.Models.NovelaPersonaje", b =>
                {
                    b.HasOne("Domain.Models.Novela", "Novela")
                        .WithMany("Personajes")
                        .HasForeignKey("NovelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Personaje", "Personaje")
                        .WithMany("Novelas")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novela");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("Domain.Models.NovelaVersion", b =>
                {
                    b.HasOne("Domain.Models.Novela", "Novela")
                        .WithMany("NovelaVersiones")
                        .HasForeignKey("NovelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novela");
                });

            modelBuilder.Entity("Domain.Models.PersonajeSprite", b =>
                {
                    b.HasOne("Domain.Models.Personaje", "Personaje")
                        .WithMany("Sprites")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("Domain.Models.Recurso", b =>
                {
                    b.HasOne("Domain.Models.BackgroundSprite", "BackgroundSprite")
                        .WithMany()
                        .HasForeignKey("BackgroundSpriteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Escena", "Escena")
                        .WithMany("Recursos")
                        .HasForeignKey("EscenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Recurso", "SiguienteRecurso")
                        .WithMany()
                        .HasForeignKey("SiguienteRecursoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BackgroundSprite");

                    b.Navigation("Escena");

                    b.Navigation("SiguienteRecurso");
                });

            modelBuilder.Entity("Domain.Models.RecursoDecisionOpcion", b =>
                {
                    b.HasOne("Domain.Models.Recurso", "RecursoDecision")
                        .WithMany("Opciones")
                        .HasForeignKey("RecursoDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Recurso", "SiguienteRecurso")
                        .WithMany()
                        .HasForeignKey("SiguienteRecursoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecursoDecision");

                    b.Navigation("SiguienteRecurso");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Background", b =>
                {
                    b.Navigation("Novelas");

                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("Domain.Models.Escena", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Domain.Models.Lectura", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Domain.Models.Novela", b =>
                {
                    b.Navigation("Backgrounds");

                    b.Navigation("NovelaVersiones");

                    b.Navigation("Personajes");
                });

            modelBuilder.Entity("Domain.Models.NovelaVersion", b =>
                {
                    b.Navigation("Escenas");
                });

            modelBuilder.Entity("Domain.Models.Personaje", b =>
                {
                    b.Navigation("Novelas");

                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("Domain.Models.Recurso", b =>
                {
                    b.Navigation("Lecturas");

                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Navigation("Lecturas");

                    b.Navigation("NovelasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
