name: Build and Push Backend to Docker Hub

on:
  push:
    branches: [ "main" ] # Se dispara al hacer push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código fuente
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configurar el motor de construcción (Buildx) necesario para la caché
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Autenticarse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Generar etiquetas automáticas (ej. tu-usuario/api:latest y tu-usuario/api:sha-12345)
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/creanovel-dotnet # <- nombre de repo en Docker Hub
        tags: |
          type=raw,value=latest
          type=sha,format=short

    # 5. Construir y subir la imagen usando la caché de GitHub Actions
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # Lee la caché guardada en GitHub Actions
        cache-to: type=gha,mode=max # Guarda la nueva caché en GitHub Actions